dojo._xdResourceLoaded({depends:[["provide","dojox.widget.FileInputAuto"],["require","dojox.widget.FileInput"],["require","dojo.io.iframe"]],defineResource:function(A){if(!A._hasResource["dojox.widget.FileInputAuto"]){A._hasResource["dojox.widget.FileInputAuto"]=true;
A.provide("dojox.widget.FileInputAuto");
A.require("dojox.widget.FileInput");
A.require("dojo.io.iframe");
A.declare("dojox.widget.FileInputAuto",dojox.widget.FileInput,{url:"",blurDelay:2000,duration:500,uploadMessage:"Uploading ...",_sent:false,templateString:'<div class="dijitFileInput">\r\n\t<input class="dijitFileInputReal" type="file" dojoAttachPoint="fileInput" />\r\n\t<div class="dijitFakeInput" dojoAttachPoint="fakeNodeHolder">\r\n\t\t<input class="dijitFileInputVisible" type="text" dojoAttachPoint="focusNode, inputNode" />\r\n\t\t<span class="dijitInline dijitFileInputText" dojoAttachPoint="titleNode">${label}</span>\r\n\t\t<span class="dijitInline dijitFileInputButton" dojoAttachPoint="cancelNode" dojoAttachEvent="onclick:_onClick">${cancelText}</span>\r\n\t</div>\r\n\t<div class="dijitProgressOverlay" dojoAttachPoint="overlay">&nbsp;</div>\r\n</div>\r\n',startup:function(){this._blurListener=A.connect(this.fileInput,"onblur",this,"_onBlur");
this._focusListener=A.connect(this.fileInput,"onfocus",this,"_onFocus");
this.inherited("startup",arguments)
},_onFocus:function(){if(this._blurTimer){clearTimeout(this._blurTimer)
}},_onBlur:function(){if(this._blurTimer){clearTimeout(this._blurTimer)
}if(!this._sent){this._blurTimer=setTimeout(A.hitch(this,"_sendFile"),this.blurDelay)
}},setMessage:function(B){if(!A.isIE){this.overlay.innerHTML=B
}},_sendFile:function(D){if(!this.fileInput.value||this._sent){return 
}A.style(this.fakeNodeHolder,"display","none");
A.style(this.overlay,"opacity","0");
A.style(this.overlay,"display","block");
this.setMessage(this.uploadMessage);
A.fadeIn({node:this.overlay,duration:this.duration}).play();
var B=document.createElement("form");
B.setAttribute("enctype","multipart/form-data");
var C=A.clone(this.fileInput);
B.appendChild(this.fileInput);
A.body().appendChild(B);
A.io.iframe.send({url:this.url+"?name="+this.name,form:B,handleAs:"text",handle:A.hitch(this,"_handleSend")})
},_handleSend:function(C,B){if(!A.isIE){this.overlay.innerHTML=""
}this._sent=true;
A.style(this.overlay,"opacity","0");
A.style(this.overlay,"border","none");
A.style(this.overlay,"background","none");
this.overlay.style.backgroundImage="none";
this.fileInput.style.display="none";
this.fakeNodeHolder.style.display="none";
A.fadeIn({node:this.overlay,duration:this.duration}).play(250);
A.disconnect(this._blurListener);
A.disconnect(this._focusListener);
this.onComplete(C,B,this)
},_onClick:function(B){if(this._blurTimer){clearTimeout(this._blurTimer)
}A.disconnect(this._blurListener);
A.disconnect(this._focusListener);
this.inherited("_onClick",arguments);
this._blurListener=A.connect(this.fileInput,"onblur",this,"_onBlur");
this._focusListener=A.connect(this.fileInput,"onfocus",this,"_onFocus")
},onComplete:function(D,C,B){}});
A.declare("dojox.widget.FileInputBlind",dojox.widget.FileInputAuto,{startup:function(){this.inherited("startup",arguments);
this._off=A.style(this.inputNode,"width");
this.inputNode.style.display="none";
this._fixPosition()
},_fixPosition:function(){if(A.isIE){A.style(this.fileInput,"width","1px")
}else{A.style(this.fileInput,"left","-"+(this._off)+"px")
}},_onClick:function(B){this.inherited("_onClick",arguments);
this._fixPosition()
}})
}}});