dojo._xdResourceLoaded({depends:[["provide","dojox.widget.Loader"],["require","dijit._Widget"],["require","dijit._Templated"]],defineResource:function(A){if(!A._hasResource["dojox.widget.Loader"]){A._hasResource["dojox.widget.Loader"]=true;
A.provide("dojox.widget.Loader");
A.experimental("dojox.widget.Loader");
A.require("dijit._Widget");
A.require("dijit._Templated");
A.declare("dojox.widget.Loader",[dijit._Widget,dijit._Templated],{loadIcon:A.moduleUrl("dojox.widget.Loader","icons/loading.gif"),loadMessage:"Loading ...",hasVisuals:true,attachToPointer:true,duration:125,_offset:16,_pointerConnect:null,_xhrStart:null,_xhrEnd:null,templateString:'<div dojoAttachPoint="loadNode" class="dojoxLoader"><img src="${loadIcon}" class="dojoxLoaderIcon"> <span dojoAttachPoint="loadMessageNode" class="dojoxLoaderMessage"></span></div>',postCreate:function(){if(!this.hasVisuals){this.loadNode.style.display="none"
}else{if(this.attachToPointer){A.removeClass(this.loadNode,"dojoxLoader");
A.addClass(this.loadNode,"dojoxLoaderPointer")
}this._hide()
}this._setMessage(this.loadMessage);
this._xhrStart=A.connect(A,"_ioSetArgs",this,"_show");
this._xhrEnd=A.connect(A.Deferred.prototype,"_fire",this,"_hide")
},_setMessage:function(B){this.loadMessageNode.innerHTML=B
},_putLoader:function(B){dijit.placeOnScreen(this.loadNode,{x:B.clientX+this._offset,y:B.clientY+this._offset},["TL","BR"])
},_show:function(){A.publish("Loader",[{message:"started"}]);
if(this.hasVisuals){if(this.attachToPointer){this._pointerConnect=A.connect(document,"onmousemove",this,"_putLoader")
}A.fadeIn({node:this.loadNode,duration:this.duration}).play()
}},_hide:function(){A.publish("Loader",[{message:"ended"}]);
if(this.hasVisuals){if(this.attachPointer){A.disconnect(this._pointerConnect)
}A.fadeOut({node:this.loadNode,duration:this.duration}).play()
}}})
}}});