if(!dojo._hasResource["dojox.grid._grid.focus"]){dojo._hasResource["dojox.grid._grid.focus"]=true;
dojo.provide("dojox.grid._grid.focus");
dojo.declare("dojox.grid.focus",null,{constructor:function(A){this.grid=A;
this.cell=null;
this.rowIndex=-1;
dojo.connect(this.grid.domNode,"onfocus",this,"doFocus")
},tabbingOut:false,focusClass:"dojoxGrid-cell-focus",focusView:null,initFocusView:function(){this.focusView=this.grid.views.getFirstScrollingView()
},isFocusCell:function(A,B){return(this.cell==A)&&(this.rowIndex==B)
},isLastFocusCell:function(){return(this.rowIndex==this.grid.rowCount-1)&&(this.cell.index==this.grid.layout.cellCount-1)
},isFirstFocusCell:function(){return(this.rowIndex==0)&&(this.cell.index==0)
},isNoFocusCell:function(){return(this.rowIndex<0)||!this.cell
},_focusifyCellNode:function(A){var C=this.cell&&this.cell.getNode(this.rowIndex);
if(C){dojo.toggleClass(C,this.focusClass,A);
this.scrollIntoView();
try{if(!this.grid.edit.isEditing()){dojox.grid.fire(C,"focus")
}}catch(B){}}},scrollIntoView:function(){if(!this.cell){return 
}var F=this.cell,C=F.view.scrollboxNode,B={w:C.clientWidth,l:C.scrollLeft,t:C.scrollTop,h:C.clientHeight},E=F.getNode(this.rowIndex),D=F.view.getRowNode(this.rowIndex),A=this.grid.scroller.findScrollTop(this.rowIndex);
if(E.offsetLeft+E.offsetWidth>B.l+B.w){C.scrollLeft=E.offsetLeft+E.offsetWidth-B.w
}else{if(E.offsetLeft<B.l){C.scrollLeft=E.offsetLeft
}}if(A+D.offsetHeight>B.t+B.h){this.grid.setScrollTop(A+D.offsetHeight-B.h)
}else{if(A<B.t){this.grid.setScrollTop(A)
}}},styleRow:function(A){if(A.index==this.rowIndex){this._focusifyCellNode(true)
}},setFocusIndex:function(B,A){this.setFocusCell(this.grid.getCell(A),B)
},setFocusCell:function(A,B){if(A&&!this.isFocusCell(A,B)){this.tabbingOut=false;
this.focusGrid();
this._focusifyCellNode(false);
this.cell=A;
this.rowIndex=B;
this._focusifyCellNode(true)
}if(dojo.isOpera){setTimeout(dojo.hitch(this.grid,"onCellFocus",this.cell,this.rowIndex),1)
}else{this.grid.onCellFocus(this.cell,this.rowIndex)
}},next:function(){var C=this.rowIndex,A=this.cell.index+1,D=this.grid.layout.cellCount-1,B=this.grid.rowCount-1;
if(A>D){A=0;
C++
}if(C>B){A=D;
C=B
}this.setFocusIndex(C,A)
},previous:function(){var B=(this.rowIndex||0),A=(this.cell.index||0)-1;
if(A<0){A=this.grid.layout.cellCount-1;
B--
}if(B<0){B=0;
A=0
}this.setFocusIndex(B,A)
},move:function(D,A){var F=this.grid.rowCount-1,H=this.grid.layout.cellCount-1,E=this.rowIndex,C=this.cell.index,G=Math.min(F,Math.max(0,E+D)),B=Math.min(H,Math.max(0,C+A));
this.setFocusIndex(G,B);
if(D){this.grid.updateRow(E)
}},previousKey:function(A){if(this.isFirstFocusCell()){this.tabOut(this.grid.domNode)
}else{dojo.stopEvent(A);
this.previous()
}},nextKey:function(A){if(this.isLastFocusCell()){this.tabOut(this.grid.lastFocusNode)
}else{dojo.stopEvent(A);
this.next()
}},tabOut:function(A){this.tabbingOut=true;
A.focus()
},focusGrid:function(){dojox.grid.fire(this.focusView,"focus");
this._focusifyCellNode(true)
},doFocus:function(A){if(A&&A.target!=A.currentTarget){return 
}if(!this.tabbingOut&&this.isNoFocusCell()){this.setFocusIndex(0,0)
}this.tabbingOut=false
}})
};