dojo._xdResourceLoaded({depends:[["provide","dijit.layout.LayoutContainer"],["require","dijit.layout._LayoutWidget"]],defineResource:function(A){if(!A._hasResource["dijit.layout.LayoutContainer"]){A._hasResource["dijit.layout.LayoutContainer"]=true;
A.provide("dijit.layout.LayoutContainer");
A.require("dijit.layout._LayoutWidget");
A.declare("dijit.layout.LayoutContainer",dijit.layout._LayoutWidget,{layout:function(){dijit.layout.layoutChildren(this.domNode,this._contentBox,this.getChildren())
},addChild:function(C,B){dijit._Container.prototype.addChild.apply(this,arguments);
if(this._started){dijit.layout.layoutChildren(this.domNode,this._contentBox,this.getChildren())
}},removeChild:function(B){dijit._Container.prototype.removeChild.apply(this,arguments);
if(this._started){dijit.layout.layoutChildren(this.domNode,this._contentBox,this.getChildren())
}}});
A.extend(dijit._Widget,{layoutAlign:"none"})
}}});