dojo._xdResourceLoaded({depends:[["provide","dijit._base.typematic"]],defineResource:function(B){if(!B._hasResource["dijit._base.typematic"]){B._hasResource["dijit._base.typematic"]=true;
B.provide("dijit._base.typematic");
dijit.typematic={_fireEventAndReload:function(){this._timer=null;
this._callback(++this._count,this._node,this._evt);
this._currentTimeout=(this._currentTimeout<0)?this._initialDelay:((this._subsequentDelay>1)?this._subsequentDelay:Math.round(this._currentTimeout*this._subsequentDelay));
this._timer=setTimeout(B.hitch(this,"_fireEventAndReload"),this._currentTimeout)
},trigger:function(N,A,L,I,J,M,K){if(J!=this._obj){this.stop();
this._initialDelay=K||500;
this._subsequentDelay=M||0.9;
this._obj=J;
this._evt=N;
this._node=L;
this._currentTimeout=-1;
this._count=-1;
this._callback=B.hitch(A,I);
this._fireEventAndReload()
}},stop:function(){if(this._timer){clearTimeout(this._timer);
this._timer=null
}if(this._obj){this._callback(-1,this._node,this._evt);
this._obj=null
}},addKeyListener:function(J,L,A,H,K,I){return[B.connect(J,"onkeypress",this,function(C){if(C.keyCode==L.keyCode&&(!L.charCode||L.charCode==C.charCode)&&(L.ctrlKey===undefined||L.ctrlKey==C.ctrlKey)&&(L.altKey===undefined||L.altKey==C.ctrlKey)&&(L.shiftKey===undefined||L.shiftKey==C.ctrlKey)){B.stopEvent(C);
dijit.typematic.trigger(L,A,J,H,L,K,I)
}else{if(dijit.typematic._obj==L){dijit.typematic.stop()
}}}),B.connect(J,"onkeyup",this,function(C){if(dijit.typematic._obj==L){dijit.typematic.stop()
}})]
},addMouseListener:function(J,A,H,K,I){var L=B.connect;
return[L(J,"mousedown",this,function(C){B.stopEvent(C);
dijit.typematic.trigger(C,A,J,H,J,K,I)
}),L(J,"mouseup",this,function(C){B.stopEvent(C);
dijit.typematic.stop()
}),L(J,"mouseout",this,function(C){B.stopEvent(C);
dijit.typematic.stop()
}),L(J,"mousemove",this,function(C){B.stopEvent(C)
}),L(J,"dblclick",this,function(C){B.stopEvent(C);
if(B.isIE){dijit.typematic.trigger(C,A,J,H,J,K,I);
setTimeout(dijit.typematic.stop,50)
}})]
},addListener:function(K,J,N,A,I,M,L){return this.addKeyListener(J,N,A,I,M,L).concat(this.addMouseListener(K,A,I,M,L))
}}
}}});