dojo._xdResourceLoaded({depends:[["provide","dijit._base.typematic"]],defineResource:function(A){if(!A._hasResource["dijit._base.typematic"]){A._hasResource["dijit._base.typematic"]=true;
A.provide("dijit._base.typematic");
dijit.typematic={_fireEventAndReload:function(){this._timer=null;
this._callback(++this._count,this._node,this._evt);
this._currentTimeout=(this._currentTimeout<0)?this._initialDelay:((this._subsequentDelay>1)?this._subsequentDelay:Math.round(this._currentTimeout*this._subsequentDelay));
this._timer=setTimeout(A.hitch(this,"_fireEventAndReload"),this._currentTimeout)
},trigger:function(B,H,D,G,F,C,E){if(F!=this._obj){this.stop();
this._initialDelay=E||500;
this._subsequentDelay=C||0.9;
this._obj=F;
this._evt=B;
this._node=D;
this._currentTimeout=-1;
this._count=-1;
this._callback=A.hitch(H,G);
this._fireEventAndReload()
}},stop:function(){if(this._timer){clearTimeout(this._timer);
this._timer=null
}if(this._obj){this._callback(-1,this._node,this._evt);
this._obj=null
}},addKeyListener:function(D,B,G,F,C,E){return[A.connect(D,"onkeypress",this,function(H){if(H.keyCode==B.keyCode&&(!B.charCode||B.charCode==H.charCode)&&(B.ctrlKey===undefined||B.ctrlKey==H.ctrlKey)&&(B.altKey===undefined||B.altKey==H.ctrlKey)&&(B.shiftKey===undefined||B.shiftKey==H.ctrlKey)){A.stopEvent(H);
dijit.typematic.trigger(B,G,D,F,B,C,E)
}else{if(dijit.typematic._obj==B){dijit.typematic.stop()
}}}),A.connect(D,"onkeyup",this,function(H){if(dijit.typematic._obj==B){dijit.typematic.stop()
}})]
},addMouseListener:function(D,G,F,C,E){var B=A.connect;
return[B(D,"mousedown",this,function(H){A.stopEvent(H);
dijit.typematic.trigger(H,G,D,F,D,C,E)
}),B(D,"mouseup",this,function(H){A.stopEvent(H);
dijit.typematic.stop()
}),B(D,"mouseout",this,function(H){A.stopEvent(H);
dijit.typematic.stop()
}),B(D,"mousemove",this,function(H){A.stopEvent(H)
}),B(D,"dblclick",this,function(H){A.stopEvent(H);
if(A.isIE){dijit.typematic.trigger(H,G,D,F,D,C,E);
setTimeout(dijit.typematic.stop,50)
}})]
},addListener:function(E,F,B,H,G,C,D){return this.addKeyListener(F,B,H,G,C,D).concat(this.addMouseListener(E,H,G,C,D))
}}
}}});