dojo._xdResourceLoaded({depends:[["provide","dijit._base"],["require","dijit._base.focus"],["require","dijit._base.manager"],["require","dijit._base.place"],["require","dijit._base.popup"],["require","dijit._base.scroll"],["require","dijit._base.sniff"],["require","dijit._base.bidi"],["require","dijit._base.typematic"],["require","dijit._base.wai"],["require","dijit._base.window"]],defineResource:function(A){if(!A._hasResource["dijit._base"]){A._hasResource["dijit._base"]=true;
A.provide("dijit._base");
A.require("dijit._base.focus");
A.require("dijit._base.manager");
A.require("dijit._base.place");
A.require("dijit._base.popup");
A.require("dijit._base.scroll");
A.require("dijit._base.sniff");
A.require("dijit._base.bidi");
A.require("dijit._base.typematic");
A.require("dijit._base.wai");
A.require("dijit._base.window")
}}});