dojo._xdResourceLoaded({depends:[["provide","dojox.widget.FileInput"],["require","dijit.form._FormWidget"],["require","dijit._Templated"]],defineResource:function(B){if(!B._hasResource["dojox.widget.FileInput"]){B._hasResource["dojox.widget.FileInput"]=true;
B.provide("dojox.widget.FileInput");
B.experimental("dojox.widget.FileInput");
B.require("dijit.form._FormWidget");
B.require("dijit._Templated");
B.declare("dojox.widget.FileInput",[dijit.form._FormWidget,dijit._Templated],{label:"Browse ...",cancelText:"Cancel",name:"uploadFile",templateString:'<div class="dijitFileInput">\r\n\t<input id="${id}" class="dijitFileInputReal" type="file" dojoAttachPoint="fileInput" name="${name}" />\r\n\t<div class="dijitFakeInput">\r\n\t\t<input class="dijitFileInputVisible" type="text" dojoAttachPoint="focusNode, inputNode" />\r\n\t\t<span class="dijitFileInputText" dojoAttachPoint="titleNode">${label}</span>\r\n\t\t<span class="dijitFileInputButton" dojoAttachPoint="cancelNode" \r\n\t\t\tdojoAttachEvent="onclick:_onClick">${cancelText}</span>\r\n\t</div>\r\n</div>\r\n',startup:function(){this.inherited("startup",arguments);
this._listener=B.connect(this.fileInput,"onchange",this,"_matchValue");
this._keyListener=B.connect(this.fileInput,"onkeyup",this,"_matchValue")
},_matchValue:function(){this.inputNode.value=this.fileInput.value;
if(this.inputNode.value){this.cancelNode.style.visibility="visible";
B.fadeIn({node:this.cancelNode,duration:275}).play()
}},setLabel:function(A,D){this.titleNode.innerHTML=A
},_onClick:function(A){B.disconnect(this._listener);
B.disconnect(this._keyListener);
this.domNode.removeChild(this.fileInput);
B.fadeOut({node:this.cancelNode,duration:275}).play();
this.fileInput=document.createElement("input");
this.fileInput.setAttribute("type","file");
this.fileInput.setAttribute("id",this.id);
this.fileInput.setAttribute("name",this.name);
B.addClass(this.fileInput,"dijitFileInputReal");
this.domNode.appendChild(this.fileInput);
this._keyListener=B.connect(this.fileInput,"onkeyup",this,"_matchValue");
this._listener=B.connect(this.fileInput,"onchange",this,"_matchValue");
this.inputNode.value=""
}})
}}});