dojo._xdResourceLoaded({depends:[["provide","dojox.widget.FileInputAuto"],["require","dojox.widget.FileInput"],["require","dojo.io.iframe"]],defineResource:function(B){if(!B._hasResource["dojox.widget.FileInputAuto"]){B._hasResource["dojox.widget.FileInputAuto"]=true;
B.provide("dojox.widget.FileInputAuto");
B.require("dojox.widget.FileInput");
B.require("dojo.io.iframe");
B.declare("dojox.widget.FileInputAuto",dojox.widget.FileInput,{url:"",blurDelay:2000,duration:500,uploadMessage:"Uploading ...",_sent:false,templateString:'<div class="dijitFileInput">\r\n\t<input class="dijitFileInputReal" type="file" dojoAttachPoint="fileInput" />\r\n\t<div class="dijitFakeInput" dojoAttachPoint="fakeNodeHolder">\r\n\t\t<input class="dijitFileInputVisible" type="text" dojoAttachPoint="focusNode, inputNode" />\r\n\t\t<span class="dijitInline dijitFileInputText" dojoAttachPoint="titleNode">${label}</span>\r\n\t\t<span class="dijitInline dijitFileInputButton" dojoAttachPoint="cancelNode" dojoAttachEvent="onclick:_onClick">${cancelText}</span>\r\n\t</div>\r\n\t<div class="dijitProgressOverlay" dojoAttachPoint="overlay">&nbsp;</div>\r\n</div>\r\n',startup:function(){this._blurListener=B.connect(this.fileInput,"onblur",this,"_onBlur");
this._focusListener=B.connect(this.fileInput,"onfocus",this,"_onFocus");
this.inherited("startup",arguments)
},_onFocus:function(){if(this._blurTimer){clearTimeout(this._blurTimer)
}},_onBlur:function(){if(this._blurTimer){clearTimeout(this._blurTimer)
}if(!this._sent){this._blurTimer=setTimeout(B.hitch(this,"_sendFile"),this.blurDelay)
}},setMessage:function(A){if(!B.isIE){this.overlay.innerHTML=A
}},_sendFile:function(A){if(!this.fileInput.value||this._sent){return 
}B.style(this.fakeNodeHolder,"display","none");
B.style(this.overlay,"opacity","0");
B.style(this.overlay,"display","block");
this.setMessage(this.uploadMessage);
B.fadeIn({node:this.overlay,duration:this.duration}).play();
var F=document.createElement("form");
F.setAttribute("enctype","multipart/form-data");
var E=B.clone(this.fileInput);
F.appendChild(this.fileInput);
B.body().appendChild(F);
B.io.iframe.send({url:this.url+"?name="+this.name,form:F,handleAs:"text",handle:B.hitch(this,"_handleSend")})
},_handleSend:function(A,D){if(!B.isIE){this.overlay.innerHTML=""
}this._sent=true;
B.style(this.overlay,"opacity","0");
B.style(this.overlay,"border","none");
B.style(this.overlay,"background","none");
this.overlay.style.backgroundImage="none";
this.fileInput.style.display="none";
this.fakeNodeHolder.style.display="none";
B.fadeIn({node:this.overlay,duration:this.duration}).play(250);
B.disconnect(this._blurListener);
B.disconnect(this._focusListener);
this.onComplete(A,D,this)
},_onClick:function(A){if(this._blurTimer){clearTimeout(this._blurTimer)
}B.disconnect(this._blurListener);
B.disconnect(this._focusListener);
this.inherited("_onClick",arguments);
this._blurListener=B.connect(this.fileInput,"onblur",this,"_onBlur");
this._focusListener=B.connect(this.fileInput,"onfocus",this,"_onFocus")
},onComplete:function(A,E,F){}});
B.declare("dojox.widget.FileInputBlind",dojox.widget.FileInputAuto,{startup:function(){this.inherited("startup",arguments);
this._off=B.style(this.inputNode,"width");
this.inputNode.style.display="none";
this._fixPosition()
},_fixPosition:function(){if(B.isIE){B.style(this.fileInput,"width","1px")
}else{B.style(this.fileInput,"left","-"+(this._off)+"px")
}},_onClick:function(A){this.inherited("_onClick",arguments);
this._fixPosition()
}})
}}});