dojo._xdResourceLoaded({depends:[["provide","dojo._base"],["require","dojo._base.lang"],["require","dojo._base.declare"],["require","dojo._base.connect"],["require","dojo._base.Deferred"],["require","dojo._base.json"],["require","dojo._base.array"],["require","dojo._base.Color"],["requireIf",dojo.isBrowser,"dojo._base.window"],["requireIf",dojo.isBrowser,"dojo._base.event"],["requireIf",dojo.isBrowser,"dojo._base.html"],["requireIf",dojo.isBrowser,"dojo._base.NodeList"],["requireIf",dojo.isBrowser,"dojo._base.query"],["requireIf",dojo.isBrowser,"dojo._base.xhr"],["requireIf",dojo.isBrowser,"dojo._base.fx"]],defineResource:function(A){if(!A._hasResource["dojo._base"]){A._hasResource["dojo._base"]=true;
A.provide("dojo._base");
A.require("dojo._base.lang");
A.require("dojo._base.declare");
A.require("dojo._base.connect");
A.require("dojo._base.Deferred");
A.require("dojo._base.json");
A.require("dojo._base.array");
A.require("dojo._base.Color");
A.requireIf(A.isBrowser,"dojo._base.window");
A.requireIf(A.isBrowser,"dojo._base.event");
A.requireIf(A.isBrowser,"dojo._base.html");
A.requireIf(A.isBrowser,"dojo._base.NodeList");
A.requireIf(A.isBrowser,"dojo._base.query");
A.requireIf(A.isBrowser,"dojo._base.xhr");
A.requireIf(A.isBrowser,"dojo._base.fx");
(function(){if(djConfig.require){for(var B=0;
B<djConfig.require.length;
B++){A.require(djConfig.require[B])
}}})()
}}});